version: '3.7'

services:
    db:
        container_name: postgres
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - pupitch-backend

    redis:
        container_name: redis
        image: redis:5.0
        restart: always
        ports:
            - 6379:6379
        command: redis-server
        volumes:
            - redis_data:/data
        networks:
            - pupitch-backend

    s3:
        container_name: minio
        image: minio/minio:latest
        ports: 
          - "9000:9000"
          - "9099:9099"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        volumes:
            - minio_data:/data
        command: server --address "0.0.0.0:9099" --console-address "0.0.0.0:9000" /data
        restart: always
        networks:
            - pupitch-backend

volumes:
    postgres_data:
    redis_data:
    minio_data:

networks:
    pupitch-backend:
